[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "pydub==0.25.1",
    "requests>=2.32.4",
    "speechrecognition>=3.14.3",
    "telethon>=1.40.0",
]
